FROM python:3.11-slim
WORKDIR /app
COPY requirements/requirements-trigger-worker.txt .
RUN pip install --no-cache-dir -r requirements-trigger-worker.txt
COPY execution/ ./execution/
COPY experience/ ./experience/
COPY performance/ ./performance/
CMD ["python", "-m", "performance.trigger_worker"]
